#!/usr/bin/python

##																		 ##
## CHANGE THIS FILENAME TO settings.py ##
##																		 ##

MONGO_HOST     = "YOUR_SERVER_NAME"
MONGO_PORT     =  YOUR_PORT
MONGO_USERNAME = "YOUR_SERVER_USER_NAME"
MONGO_PASSWORD = "YOUR_SERVER_PASSWORD"
MONGO_DBNAME   = "YOUR_DB_NAME"

APP_SECRET_KEY = "YOUR_APP_SPECIFIC_SECRET_KEY"
PASSWORD_SALT  = ""
